### ISSUE TITLE
Failed building project

### ISSUE THREAD

**Issue by meichengg** [secretkeysio/subatomic#1]
Hi, i wonder if this project is discontinued?

I'm having this problem when building from source code.

![image](https://user-images.githubusercontent.com/25204246/219580342-125e1859-ce34-4c15-9f61-0bd7045db80c.png)

**Comment by ryanmcgrath** [comment]
`cacao` has seen significant changes since this app was built, and it worked for Protonmail's old codebase so I frankly am not even sure it'd work with the new one. Should probably just archive the repo...

**Comment by meichengg** [comment]
So you are not updating the app? 😭

**Comment by ryanmcgrath** [comment]
I'd be happy to advise anyone who wants to revive it, though it's also worth noting that this project was built before Tauri was a thing - a newer project might honestly have an easier time building a PM wrapper app via that.

**Comment by meichengg** [comment]
I was looking for ElectronMail's alternative because i just hate Electron so bad and found your repo, i think it's cool though, hope you can revive this thing 👍🏻

**Comment by ryanmcgrath** [comment]
If someone wants to continue it, I did the (basic) work of updating it to cacao `0.3.2`. You can see the branch here: https://github.com/secretkeysio/subatomic/tree/cacao-0.3.2

I don't personally have the time or bandwidth to work on this anymore, but there's the start if someone's down. :)

(It compiles and runs, albeit hasn't been updated since... Catalina?)
